config/routes.rb
Sandbox2::Application.routes.draw do
  resources :roles

  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  resources :tasks

  root :to => 'tasks#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role? :prosman
         can :manage, :all
       else
        can :read, :all
       end
    #
    # fff The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_many :role_assignments
  has_many :users, :through => :role_assignments
end

app/models/role_assignment.rb
class RoleAssignment < ActiveRecord::Base
  attr_accessible :role_id, :user_id
  belongs_to :user
  belongs_to :role
end

app/models/task.rb
class Task < ActiveRecord::Base

  attr_accessible :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :role_assignments
  has_many :roles, :through => :role_assignments

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @roles = Role.all
  end

  def show
    @role = Role.find(params[:id])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(params[:role])
    if @role.save
      redirect_to @role, :notice => "Successfully created role."
    else
      render :action => 'new'
    end
  end

  def edit
    @role = Role.find(params[:id])
  end

  def update
    @role = Role.find(params[:id])
    if @role.update_attributes(params[:role])
      redirect_to @role, :notice  => "Successfully updated role."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    redirect_to roles_url, :notice => "Successfully destroyed role."
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  load_and_authorize_resource

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
      redirect_to @task, :notice => "Successfully created task."
    else
      render :action => 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to @task, :notice  => "Successfully updated task."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url, :notice => "Successfully destroyed task."
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication

  def check_permissions
    authorize! :create, resource
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag 'blueprint/screen', :media => "screen, projection" %>
    <%= stylesheet_link_tag 'blueprint/print', :media => "print" %>



    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>

    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="main">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/roles/_form.html.erb
<%= form_for @role do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/roles/edit.html.erb
<% title "Edit Role" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @role %> |
  <%= link_to "View All", roles_path %>
</p>

app/views/roles/index.html.erb
<% title "Roles" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for role in @roles %>
    <tr>
      <td><%= role.name %></td>
      <td><%= link_to "Show", role %></td>
      <td><%= link_to "Edit", edit_role_path(role) %></td>
      <td><%= link_to "Destroy", role, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Role", new_role_path %></p>

app/views/roles/new.html.erb
<% title "New Role" %>

<%= render 'form' %>

<p><%= link_to "Back to List", roles_path %></p>

app/views/roles/show.html.erb
<% title "Role" %>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <%= link_to "Edit", edit_role_path(@role) %> |
  <%= link_to "Destroy", @role, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", roles_path %>
</p>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/tasks/edit.html.erb
<% title "Edit Task" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @task %> |
  <%= link_to "View All", tasks_path %>
</p>

app/views/tasks/index.html.erb
<% title "Tasks" %>

<table>
  <tr>
    <th>Title</th>
  </tr>
  <% for task in @tasks %>
    <tr>
      <td><%= task.title %></td>
      <td><%= link_to "Show", task %></td>
      <td><%= link_to "Edit", edit_task_path(task) %></td>
      <td><%= link_to "Destroy", task, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Task", new_task_path %></p>

app/views/tasks/new.html.erb
<% title "New Task" %>

<%= render 'form' %>

<p><%= link_to "Back to List", tasks_path %></p>

app/views/tasks/show.html.erb
<% title "Task" %>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <%= link_to "Edit", edit_task_path(@task) %> |
  <%= link_to "Destroy", @task, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", tasks_path %>
</p>